# Generated by Django 3.0.5 on 2022-12-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20221220_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
